# Generated by Django 4.2.7 on 2024-03-13 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=100)),
                ("level", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="tour",
            name="animals",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="path",
        ),
        migrations.RemoveField(
            model_name="zookeeper",
            name="image",
        ),
        migrations.AddField(
            model_name="tour",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination1",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination1",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination10",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination10",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination2",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination2",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination3",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination3",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination4",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination4",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination5",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination5",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination6",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination6",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination7",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination7",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination8",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination8",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="destination9",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination9",
                to="digitalzoo.habitat",
            ),
        ),
        migrations.AddField(
            model_name="zookeeper",
            name="img",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="carelog",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habitat",
            name="image",
            field=models.URLField(blank=True, default=""),
        ),
    ]
