# Generated by Django 4.2.7 on 2024-03-13 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0002_membership_remove_tour_animals_remove_tour_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zookeeper",
            name="img",
        ),
    ]
