# Generated by Django 4.2.7 on 2024-03-15 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "digitalzoo",
            "0004_alter_tour_destination1_alter_tour_destination10_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TourRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TourRouteDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "habitat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalzoo.habitat",
                    ),
                ),
                (
                    "tour_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalzoo.tourroute",
                    ),
                ),
            ],
            options={
                "unique_together": {("tour_route", "position")},
            },
        ),
        migrations.RenameModel(
            old_name="Membership",
            new_name="User",
        ),
        migrations.DeleteModel(
            name="Tour",
        ),
        migrations.AddField(
            model_name="tourroute",
            name="habitats",
            field=models.ManyToManyField(
                through="digitalzoo.TourRouteDetail", to="digitalzoo.habitat"
            ),
        ),
    ]
