# Generated by Django 4.2.7 on 2024-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digitalzoo",
            "0005_tourroute_tourroutedetail_rename_membership_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "ticket_period",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("year", "year"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("adult", "adult"), ("child", "child")], max_length=10
                    ),
                ),
                ("points", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
