# Generated by Django 4.2.7 on 2024-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0007_activity_activityparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityparticipant",
            name="animal",
            field=models.ManyToManyField(blank=True, to="digitalzoo.animal"),
        ),
        migrations.RemoveField(
            model_name="activityparticipant",
            name="habitat",
        ),
        migrations.RemoveField(
            model_name="activityparticipant",
            name="member",
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="habitat",
            field=models.ManyToManyField(blank=True, to="digitalzoo.habitat"),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="member",
            field=models.ManyToManyField(blank=True, to="digitalzoo.member"),
        ),
    ]
