# Generated by Django 4.2.7 on 2024-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0009_alter_activityparticipant_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="animal",
            field=models.ManyToManyField(blank=True, to="digitalzoo.animal"),
        ),
        migrations.AddField(
            model_name="activity",
            name="habitat",
            field=models.ManyToManyField(blank=True, to="digitalzoo.habitat"),
        ),
        migrations.AddField(
            model_name="activity",
            name="member",
            field=models.ManyToManyField(blank=True, to="digitalzoo.member"),
        ),
        migrations.DeleteModel(
            name="ActivityParticipant",
        ),
    ]
