# Generated by Django 4.2.7 on 2024-03-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digitalzoo",
            "0010_activity_animal_activity_habitat_activity_member_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="zookeeper",
            name="image",
            field=models.URLField(blank=True, default=""),
        ),
    ]
