# Generated by Django 4.2.7 on 2024-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0011_zookeeper_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tourschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("description", models.CharField(default="", max_length=1000)),
                (
                    "habitats",
                    models.ManyToManyField(blank=True, to="digitalzoo.habitat"),
                ),
                ("members", models.ManyToManyField(blank=True, to="digitalzoo.member")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="tourroutedetail",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tourroutedetail",
            name="habitat",
        ),
        migrations.RemoveField(
            model_name="tourroutedetail",
            name="tour_route",
        ),
        migrations.DeleteModel(
            name="TourRoute",
        ),
        migrations.DeleteModel(
            name="TourRouteDetail",
        ),
    ]
