# Generated by Django 4.2.7 on 2024-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "digitalzoo",
            "0012_tourschedule_alter_tourroutedetail_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tourschedule",
            name="guided_tours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tourschedule",
            name="habitat_availability",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tourschedule",
            name="visitor_feedback",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
