# Generated by Django 4.2.7 on 2024-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digitalzoo", "0013_tourschedule_guided_tours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourschedule",
            name="guided_tours",
        ),
        migrations.CreateModel(
            name="GuidedTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("description", models.CharField(default="", max_length=1000)),
                (
                    "habitats",
                    models.ManyToManyField(blank=True, to="digitalzoo.habitat"),
                ),
                ("members", models.ManyToManyField(blank=True, to="digitalzoo.member")),
            ],
        ),
        migrations.AddField(
            model_name="tourschedule",
            name="guided_tours",
            field=models.ManyToManyField(blank=True, to="digitalzoo.guidedtour"),
        ),
    ]
